services:
  - type: web
    name: stayfinder-backend
    rootDir: stayfinder-backend
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

build:
  environment:
    NODE_VERSION: 18.20.0
